routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pds-records', function () {
     return view('pds.index');
})->name('pds-records');

Route::get('/manage-users', function () {
     return view('user.index');
})->name('manage-users');

Route::get('/reports', function () {
     return view('report.index');
})->name('reports');

Route::get('/records', function () {
     return view('record.index');
})->name('records');

// RESOURCE for CRUD
Route::resource('pds-records', 'PdsRecordsController');
Route::resource('manage-users', 'ManageUsersController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'role', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/user/base.blade.php
@extends('layouts.app-template')

@section('content')

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">User Management</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Manage Users</li>
        </ol>
    </div>
</div>

@yield('action-content')

@endsection 

resources/views/user/create.blade.php
@extends('user.base')

@section('action-content')

<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card">
	            <!-- .left-right-aside-column-->
	            <div class="contact-page-aside">
	                <!-- .left-aside-column-->
	                <div class="left-aside bg-light-part">
	                    <ul class="list-style-none">
	                        <li class="box-label"><a href="javascript:void(0);">All Users <span>0</span></a></li>
	                        <li class="divider"></li>
	                        <li><a href="javascript:void(0)">Administrator <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">User <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">Guest <span>0</span></a></li>
	                    </ul>
	                </div>
	                <!-- /.left-aside-column-->
	                <div class="right-aside ">
                    <div class="col-12">

                    <div class="row">
                    	<div class="col-md-12">
					    	<div class="flash-message" id="flash-message">
							    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
							      @if(Session::has('alert-' . $msg))

							      <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
							      @endif
							    @endforeach
							</div> <!-- end .flash-message -->
					    </div>
                    </div>
                    
                    <div class="row">
	                    <div class="col-md-10">
				    		<div class="card-body">
		                        <h4 class="card-title">Add Administrator</h4>
		                        <h6 class="card-subtitle">Allows to control all the functions of the system</h6>
		                        <hr>
		                        <form method="POST" action="{{ route('manage-users.store') }}">
			            		{{csrf_field()}}

		                            <div class="form-group row">
		                                <label for="exampleInputuname3" class="col-sm-3 control-label">Name*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-user"></i></div>
	                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" placeholder="Name" required autofocus>
		                                    
		                            @if ($errors->has('name'))
	                                    <span class="invalid-feedback">
	                                        <strong>{{ $errors->first('name') }}</strong>
	                                    </span>
	                                @endif       
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="exampleInputEmail3" class="col-sm-3 control-label">E-mail*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-email"></i></div>
		                                        <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" placeholder="E-mail" required>

		                                        @if ($errors->has('email'))
					                                <span class="invalid-feedback">
					                                    <strong>{{ $errors->first('email') }}</strong>
					                                </span>
					                            @endif
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="web" class="col-sm-3 control-label">Role*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-settings"></i></div>
		                                        <!-- <input type="text" class="form-control" id="web" placeholder="Role"> -->
		                                        <select class="form-control custom-select" name="role" required="">
	                                                <option>-- Please select --</option>
	                                                <option value="Administrator">Administrator</option>
	                                                <option value="Encoder">Encoder</option>
	                                                <option value="User">User</option>
	                                            </select>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="inputPassword4" class="col-sm-3 control-label">Password*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-lock"></i></div>
		                                        <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="Password" name="password" required>

		                                         @if ($errors->has('password'))
				                                    <span class="invalid-feedback">
				                                        <strong>{{ $errors->first('password') }}</strong>
				                                    </span>
				                                @endif
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="inputPassword5" class="col-sm-3 control-label">Re Password*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-lock"></i></div>
		                                        <input id="password-confirm" type="password" placeholder="Re-type Password" class="form-control" name="password_confirmation" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <div class="col-sm-3">
		                                </div>
		                                <div class="col-sm-3">
		                                	<button type="button" class="btn btn-block btn-sm btn-outline-secondary">Cancel</button>
		                                </div>
		                                <div class="col-sm-6">
		                                    <button type="" class="btn btn-block btn-sm btn-info">Save User</button>
		                                </div>
		                            </div>
		                        </form>
		                    </div>
					    </div>
					</div>

				   

                    </div>
	                </div>
	                <!-- /.left-right-aside-column-->
	            </div>
	        </div>
	    </div>
	</div>
</div>

@endsection



	

resources/views/user/edit.blade.php
@extends('user.base')

@section('action-content')

<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card">
	            <!-- .left-right-aside-column-->
	            <div class="contact-page-aside">
	                <!-- .left-aside-column-->
	                <div class="left-aside bg-light-part">
	                    <ul class="list-style-none">
	                        <li class="box-label"><a href="javascript:void(0);">All Users <span>0</span></a></li>
	                        <li class="divider"></li>
	                        <li><a href="javascript:void(0)">Administrator <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">User <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">Guest <span>0</span></a></li>
	                    </ul>
	                </div>
	                <!-- /.left-aside-column-->
	                <div class="right-aside ">
                    <div class="col-12">

                    
                    
                    <div class="row">
	                    <div class="col-md-10">
				    		<div class="card-body">
		                        <h4 class="card-title">Update Administrator</h4>
		                        <h6 class="card-subtitle">Allows to control all the functions of the system</h6>
		                        <hr>
		                        <form role="form" method="POST" action="{{ route('manage-users.update' , ['id' => $user->id]) }}">
			            		{{csrf_field()}}

			            		<input type="hidden" name="_method" value="PATCH">
		                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

		                            <div class="form-group row">
		                                <label for="exampleInputuname3" class="col-sm-3 control-label">Name*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-user"></i></div>
	                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}" placeholder="Name" required autofocus>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="exampleInputEmail3" class="col-sm-3 control-label">E-mail*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-email"></i></div>
		                                        <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}" placeholder="E-mail" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="web" class="col-sm-3 control-label">Role*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-settings"></i></div>
		                                        <!-- <input type="text" class="form-control" id="web" placeholder="Role"> -->
		                                        <select class="form-control custom-select" name="role">
	                                                <option value="{{ $user->role }}">-- {{ $user->role }} --</option>
	                                                <option value="Administrator">Administrator</option>
	                                                <option value="Encoder">Encoder</option>
	                                                <option value="User">User</option>
	                                            </select>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="inputPassword4" class="col-sm-3 control-label">Password*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-lock"></i></div>
		                                        <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="Password" name="password" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <label for="inputPassword5" class="col-sm-3 control-label">Re Password*</label>
		                                <div class="col-sm-9">
		                                    <div class="input-group">
		                                        <div class="input-group-addon"><i class="ti-lock"></i></div>
		                                        <input id="password-confirm" type="password" placeholder="Re-type Password" class="form-control" name="password_confirmation" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="form-group row">
		                                <div class="col-sm-3">
		                                </div>
		                                <div class="col-sm-3">
		                                	<button type="button" class="btn btn-block btn-sm btn-outline-secondary">Cancel</button>
		                                </div>
		                                <div class="col-sm-6">
		                                    <button type="" class="btn btn-block btn-sm btn-info">Update User</button>
		                                </div>
		                            </div>
		                        </form>
		                    </div>
					    </div>
					</div>
                    
                    </div>
	                </div>
	                <!-- /.left-right-aside-column-->
	            </div>
	        </div>
	    </div>
	</div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('user.base')

@section('action-content')
<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card">
	            <!-- .left-right-aside-column-->
	            <div class="contact-page-aside">
	                <!-- .left-aside-column-->
	                <div class="left-aside bg-light-part">
	                    <ul class="list-style-none">
	                        <li class="box-label"><a href="javascript:void(0)">All Users <span>{{count($user)}}</span></a></li>
	                        <li class="divider"></li>
	                        <li><a href="javascript:void(0)">Administrator <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">User <span>0</span></a></li>
	                        <li><a href="javascript:void(0)">Guest <span>0</span></a></li>
	                    </ul>
	                </div>
	                <!-- /.left-aside-column-->
	                <div class="right-aside ">
                    <div class="col-12">

                    <div class="row">
                        <div class="col-md-12">
                            <div class="flash-message" id="flash-message">
                                @foreach (['danger', 'warning', 'success', 'info'] as $msg)
                                  @if(Session::has('alert-' . $msg))

                                  <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                                  @endif
                                @endforeach
                            </div> <!-- end .flash-message -->
                        </div>
                    </div>
                    
                    <div class="col-md-3 pull-right">
                        <a href="{{ route('manage-users.create') }}" class="btn btn-lg waves-effect waves-light btn-block btn-info col-lg-12 col-md-4">Add User</a>
                    </div>
                    <div class="col-md-9">
                    <h4 class="card-title">List of Administrator and Users</h4>
                    <h6 class="card-subtitle">Description <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
                    </div>

                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Role</th>
                                    <th>Email</th>
                                    <!-- <th>Date Registered</th> -->
                                    <th>Action</th>
                                </tr>
                            </thead> 
                            <tbody>
                            @foreach($user as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->role }}</td>
                                <td>{{ $user->email }}</td>
                                <!-- <td>{{ date('F d, Y', strtotime($user->created_at)) }}</td> -->
                                <td>

                                   <!--  <a href="{{ route('manage-users.edit', ['id' => $user->id]) }}" class="btn btn-xs btn-info">Update</a>
                                    <a href="" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a> -->

                                <form class="row" method="POST" action="{{ route('manage-users.destroy', ['id' => $user->id]) }}" onsubmit = "return confirm('Are you sure?')">

                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                                    <a href="{{ route('manage-users.edit', ['id' => $user->id]) }}" class="btn btn-xs btn-info">Update</a>

                                    @if ($user->name)
                                    <button type="submit" class="btn btn-xs btn-danger"> <i class="fa fa-trash"></i>
                                    </button>
                                    @endif

                                </form>

                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    </div>
	                </div>
	                <!-- /.left-right-aside-column-->
	            </div>
	        </div>
	    </div>
	</div>
</div>
@endsection