routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pds-records', function () {
     return view('pds.index');
})->name('pds-records');

Route::get('/manage-users', function () {
     return view('user.index');
})->name('manage-users');

Route::get('/reports', function () {
     return view('report.index');
})->name('reports');

Route::get('/records', function () {
     return view('record.index');
})->name('records');

// RESOURCE for CRUD
Route::resource('pds-records', 'PdsRecordsController');
Route::resource('manage-users', 'ManageUsersController');

resources/views/pds/base.blade.php
@extends('layouts.app-template')

@section('content')

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Personal Data Sheet</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item active">Personal Data Sheet</li>
        </ol>
    </div>
   <!--  <div>
        <a href="{{url('pds-records/create')}}" title="Add Record" class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-plus text-white"></i></a>
    </div> -->
</div>

@yield('action-content')

@endsection 

resources/views/pds/create.blade.php
@extends('pds.base')

@section('action-content')
<div class="container-fluid">
	<div class="row">
	    <div class="col-12">
	        <div class="card"> 
	            <div class="card-body wizard-content">
                    <div class="col-md-3 pull-right">
		                <a href="/pds-records" class="btn btn-block btn-lg btn-info col-lg-12 col-md-4 pull-right">Records</a>
		            </div>
		            <div class="col-md-9">
		                <h4 class="card-title">Add new record</h4>
		                <h6 class="card-subtitle">Description about adding data <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
	                </div>
	                <form action="{{ route('pds-records.store') }}" method="POST" class="tab-wizard wizard-circle">
            		{{csrf_field()}}
	                    
	                    <!-- Step 1 -->
	                    <h6>Personal & Background<br>Information</h6>
	                  		@include('pds.page-1')
	                    <!-- Step 2 -->
	                    <h6>Eligibility &<br>Work Experience</h6>
	                  		@include('pds.page-2')
	                    	
	                    <!-- Step 3 -->
	                    <h6>Voluntary Work &<br>Learning Development</h6>
	                  		@include('pds.page-3')
	                    
	                    <!-- Step 4 -->
	                    <h6>References</h6>
	                  		@include('pds.page-4')
	                </form>
	            </div>
	        </div>
	    </div>
	</div>
</div>

@endsection

resources/views/pds/index.blade.php
@extends('pds.base')

@section('action-content')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-md-3 pull-right">
                        <a href="{{ route('pds-records.create') }}" class="btn btn-lg waves-effect waves-light btn-block btn-info col-lg-12 col-md-4">Add Record</a>
                    </div>
                    <div class="col-md-9">
                    <h4 class="card-title">All Records</h4>
                    <h6 class="card-subtitle">Description <a href="http://www.csc.gov.ph" target="_blank"><i>CSC</i></a></h6>
                    </div>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>PDS No</th>
                                    <th>LAST NAME</th>
                                    <th>FIRST NAME</th>
                                    <th>MIDDLE INITIAL</th>
                                    <th>EXT NAME</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($pds as $value)
                            <tr>
                                <td>{{$value -> CSIDNO}}</td>
                                <td>{{$value -> SURNAME}}</td>
                                <td>{{$value -> FIRSTNAME}}</td>
                                <td>{{$value -> MIDDLENAME}}</td>
                                <td>{{$value -> NAMEEXT}}</td>
                                <td>
                                <form class="row" method="POST" action="{{ route('pds-records.destroy', ['ID' => $value->ID]) }}" onsubmit="return confirm('Are you sure?' . $value->CSIDNO)">
                                    <a href="" class="btn btn-xs btn-info">Update</a>
                                    <a href="" class="btn btn-xs btn-primary">View</a>

                                    @if ($value->ID)
                                    <button type="submit" class="btn btn-xs btn-danger"> <i class="fa fa-trash"></i>
                                    </button>
                                    @endif
                                </form>
                                </td>
                            </tr>
                            @endforeach   
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

@endsection

resources/views/pds/page-2.blade.php
<section>

<!-- IV. ELIGIBILITY -->
<h2 class="box-title text-info"><b>IV. Eligibility</b></h2>

<hr class="m-t-12 m-b-10">

<h2 class="box-title text-info"><b>IV. Work Experience</b></h2>


</section>

resources/views/pds/page-3.blade.php
<section>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="intType1">Interview Type :</label>
                <select class="custom-select form-control" id="intType1" data-placeholder="Type to search cities" name="intType1">
                    <option value="normal">Normal</option>
                    <option value="difficult">Difficult</option>
                    <option value="hard">Hard</option>
                </select>
            </div>
            <div class="form-group">
                <label for="Location1">Location :</label>
                <select class="custom-select form-control" id="Location1" name="location">
                    <option value="">Select City</option>
                    <option value="India">India</option>
                    <option value="USA">USA</option>
                    <option value="Dubai">Dubai</option>
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="jobTitle2">Interview Date :</label>
                <input type="date" class="form-control" id="jobTitle2" name="idate">
            </div>
            <div class="form-group">
                <label>Requirements :</label>
                <div class="c-inputs-stacked">
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">Employee</span> 
                    </label>
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">Contract</span> 
                    </label>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/pds/page-4.blade.php
<section>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="participants1">Confidance</label>
                <input type="text" class="form-control" id="participants1" name="con">
            </div>
            <div class="form-group">
                <label for="participants1">Result</label>
                <select class="custom-select form-control" id="participants1" name="res">
                    <option value="">Select Result</option>
                    <option value="Selected">Selected</option>
                    <option value="Rejected">Rejected</option>
                    <option value="Call Second-time">Call Second-time</option>
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="decisions1">Comments</label>
                <textarea name="decisions" id="decisions1" rows="4" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label>Rate Interviwer :</label>
                <div class="c-inputs-stacked">
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">1 star</span> 
                    </label>
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">2 star</span> 
                    </label>
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">3 star</span> 
                    </label>
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">4 star</span> 
                    </label>
                    <label class="inline custom-control custom-checkbox block">
                        <input type="checkbox" class="custom-control-input"> <span class="custom-control-indicator"></span> <span class="custom-control-description ml-0">5 star</span> 
                    </label>
                </div>
            </div>
        </div>
    </div>
</section>